### PR TITLE
Adding request.get/post to TimberSite

### PR DESCRIPTION
**Pull request by connorjburton**
**Issue**

There is no easy way to access GET/POST variables in the Twig templates

**Solution**

Add ```site.request``` array that contains ```site.request.get``` and ```site.request.post```

Eg.

/vacancies/?salary=30000

```
Requested salary: £{{site.request.get.salary}}
```

```
Requested Salary: £30000
```

### CODE REVIEW

**Comment by jarednova** [comment]
Thanks @connorjburton! I love this. My only question is whether it makes intuitive sense to make this property a child of Site. Does this merit being its own object? IE:

```twig
Requested salary: ${{request.get.salary}}
```

(also correcting that strange dollar symbol you used in yr example) :-)

**Comment by connorjburton** [comment]
Yeah ```request.get.salary``` is much better, was my first thought.

What is this $ you speak of!

**Comment by connorjburton** [comment]
Re-factored to it's own class, will test fully tomorrow.

**Comment by jarednova** [comment]
Awesome, thanks @connorjburton! The `"$"` are legal tender we use with dead kings on 'em

**Comment by connorjburton** [comment]
I've just added the required interface functions, other than that it works. One thing I noticed, the composer autoloader needs to be updated with the new class. How is that handled on Plugin update? As of now, if I just drop these files in it throws a fatal error.

**Comment by jarednova** [comment]
@connorjburton — I was able to get everything working. Are you talking about when deploying the plugin to wp.org?

**Comment by connorjburton** [comment]
Oh I guess its just pre-generated before deploying to wp.org

**Pull request merged**
