### PR TITLE
New routes

### PR DESCRIPTION
**Pull request by jarednova**
This solves #483 and separates the routing logic into its [own repo](upstatement/routes). Routing is now based on AltoRouter instead of PHP-Router

### CODE REVIEW

**Comment by SheilaRuth** [comment]
Does this mean that upgrading Timber in WordPress will break my routes-based plugin? Is there backwards compatibility, or do all routes need to be converted when upgrading? I looked at the routes repo and there isn't much documentation there.

**Comment by aristath** [comment]
@SheilaRuth Routes is now a separate plugin: https://github.com/jarednova/routes

**Comment by jarednova** [comment]
@SheilaRuth @aristath the repo is located at:

https://github.com/upstatement/routes

... @SheilaRuth: everything is still backwards compatible. However, it's officially depreciated so I recommend migrating to the new plugin for new work.

**Comment by SheilaRuth** [comment]
OK, thanks!

**Pull request merged**
