### PR TITLE
Store the menu item level as a param, custom Read More labels from <!--more--> tag, support for shortcodes when get_preview uses content

### PR DESCRIPTION
**Pull request by newkind**
This is for ease of access and can help with creating hierarchical structures

### CODE REVIEW

**Comment by jarednova** [comment]
This is great @newkind -- the next thing we need before I can merge is a test to verify the behavior. Are you familiar with (or interested in getting acquainted with) PHPUnit + unit tests?

**Comment by newkind** [comment]
@jarednova sure! i'm always happy to learn something new! i just set up the VVV but I'm having issues with getting PHPUnit to run properly with Timber. I followed the wiki instructions but they seem incomplete. Right now I'm struggling with `PHP Fatal error:  require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php'` Do I need to install wordpress tests separately ? I tried also going with `./install-wp-tests.sh wordpress_unit_tests wp wp` but looks like the http://wordpress.org/wordpress-master.tar.gz returns 404 - I might need to do some script edits ;)

**Comment by jarednova** [comment]
Hmmmm, it's been a loooooong time since I've set stuff up. Let me run through the instructions and get those in better shape so you can have at it.

**Comment by KLVTZ** [comment]
@newkind @jarednova to setup testing on your local, I suggest grabbing http://wp-cli.org/
After correct install on a proper environment, check out my quick summary guide via:

https://github.com/KLVTZ/WordPressHackersGuide/blob/master/08-unit-testing-in-wordpress/17.wordpress-testing.md

**Comment by KLVTZ** [comment]
@newkind @jarednova keep in mind that the above guide uses the param argument found in scaffold:
https://github.com/KLVTZ/WordPressGalaxy/blob/master/public/content/plugins/justin/bin/install-wp-tests.sh#L4

**Comment by newkind** [comment]
Hmm I have added a new piece of code to detect custom read more labels in the  tag, but I'm not sure why it got added by this pull request ... Anyways, another pull request is here ;)

**Comment by jarednova** [comment]
Thanks @newkind! I've merged the menu parts in and moved the stuff about shortcodes, etc. into #602 for further review and testing

**Comment by newkind** [comment]
No problem @jarednova :) I'm planning to do some more pull requests as I'm going through some Timber stuff and think that allowing a little bit more of user customization here and there would be a good thing.

**Pull request merged**
