### PR TITLE
fixing #1: comment threads are truncated if nesting level > 2

### PR DESCRIPTION
**Pull request by salaros**

### CODE REVIEW

**Comment by jarednova** [comment]
Paging @josephbergdoll -- can you test this guy out?

**Comment by josephbergdoll** [comment]
@salaros — it seems like a lot of comments got jumbled in your commit and thus the diff doesn't provide anything when trying to glance the changes you made. fix and push?

**Comment by josephbergdoll** [comment]
I pasted in your modifications from get_comments, and it looks like is_child is not saving any data to the comments_tree array.

**Comment by josephbergdoll** [comment]
Hi @salaros – I parsed through your changes and added it to the following PR – https://github.com/jarednova/timber/pull/717

this PR can be closed.

**Comment by jarednova** [comment]
This is closed by #717

**Pull request closed without merging**
