### PR TITLE
Feature/truncated comment depth

### PR DESCRIPTION
**Pull request by josephbergdoll**
This takes the “maxium comment depth” setting from Discussion and forces it on all child comments, so that all child comments are shown.

### CODE REVIEW

**Comment by josephbergdoll** [comment]
woooo lgtm

**Comment by jarednova** [comment]
Awesome, thanks @josephbergdoll for this and your other contributions to comments. Since there's some involved logic going on here -- can you add a test to verify that it's providing the correct data in a variety of circumstances?

**Comment by josephbergdoll** [comment]
@jarednova absolutely, will also update the Wiki

**Comment by josephbergdoll** [comment]
Just realized it's been over a month — woops. Will write some tests this weekend.

**Comment by lggorman** [comment]
Hi @josephbergdoll -- wondering if you had gotten a chance to take a look at tests for this?  We're hoping to merge it in soon, and don't mind writing a few tests if you don't have the bandwidth right now.

**Comment by josephbergdoll** [comment]
Hey @lggorman – don't have a ton of bandwidth at the moment and going to be out of town next week. Your efforts would be much appreciated!

**Comment by lggorman** [comment]
@josephbergdoll Merged in with #780.  Thanks!

**Comment by jarednova** [comment]
Thanks @josephbergdoll and @lggorman !

**Pull request closed without merging**
